name: Run tests
description: Checkout, install Nox, and run tests

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Nox
      run: pipx install nox

    - name: Run tests
      run: nox --session tests
